//** signup */
export const UNIFICATION_STATUS = {
	EMPTY: 'EMPTY',
	VERIFIED: 'VERIFIED',
	DUPLICATED: 'DUPLICATED',
	NOT_AVAILABLE_FORM: 'NOT_AVAILABLE_FORM'
};

export const PASSWORD_VERIFICATION_STATUS = {
	EMPTY: 'EMPTY',
	VERIFIED: 'VERIFIED',
	MISMATCHED: 'MISMATCHED'
};
